In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install hdf5storage

     |████████████████████████████████| 61kB 9.0MB/s 


In [ ]:
from keras.models import Sequential, Model
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras import backend as K
from keras.utils import np_utils, to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from scipy.spatial import distance
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import string
from scipy.io import loadmat
import hdf5storage

In [ ]:
X = loadmat("/content/drive/MyDrive/Research and Project Stuffs/BdSL/featureSeenTrain.mat")
Y = loadmat("/content/drive/MyDrive/Research and Project Stuffs/BdSL/YTrain_arr.mat")

In [ ]:
X = X['featuresSeen']
Y = Y['YTrain_arr']

In [ ]:
X.shape

(17714, 1920)

In [ ]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=109) # 70% training and 30% test

In [ ]:
y_train.shape

(14171, 20)

**SVM** 

In [ ]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

ValueError: ignored

**CNN**

In [ ]:
import keras
import tensorflow as tf
import numpy as np
import scipy.io
from keras.models import Sequential, Model
#from tensorflow.keras.models import Model
from keras.layers import Conv2D, MaxPooling2D, Activation, Embedding, Dense, Dropout, Flatten, Input,GlobalAveragePooling2D
from keras import activations
#from tensorflow.python.keras.layers.core import Dense, Dropout, Flatten
#from tensorflow.python.keras.layers import Input
from keras.optimizers import Adam, SGD
from keras.layers import LSTM
#from keras.layers import Dropout
#from keras.applications.vgg16 import VGG16
#from tensorflow.keras.applications import vgg16
from skimage.color import gray2rgb
#from tensorflow.keras.applications.inception_v3 import InceptionV3 
#from tensorflow.keras.applications import DenseNet201
#from tensorflow.keras.preprocessing import image
#from tensorflow.keras.models import Model
#from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from keras.applications import DenseNet201
from keras.applications.vgg16 import VGG16

In [ ]:
model = Sequential()
model.add(Dense(512, input_dim=1920, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(20, activation='sigmoid'))
lr_schedule = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=1e-6,
    decay_steps=10000,
    decay_rate=0.9)
opt = keras.optimizers.RMSprop(learning_rate=lr_schedule)
model.compile(optimizer= opt, loss='binary_crossentropy', metrics=['binary_accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 512)               983552    
_________________________________________________________________
dense_13 (Dense)             (None, 256)               131328    
_________________________________________________________________
dense_14 (Dense)             (None, 128)               32896     
_________________________________________________________________
dense_15 (Dense)             (None, 20)                2580      
Total params: 1,150,356
Trainable params: 1,150,356
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X_train, y_train,epochs=250, batch_size=256, validation_data=(X_test, y_test))

Epoch 1/250
56/56 [==============================] - 3s 41ms/step - loss: 0.6978 - binary_accuracy: 0.5350 - val_loss: 0.6889 - val_binary_accuracy: 0.5414
Epoch 2/250
56/56 [==============================] - 2s 38ms/step - loss: 0.6851 - binary_accuracy: 0.5464 - val_loss: 0.6775 - val_binary_accuracy: 0.5531
Epoch 3/250
56/56 [==============================] - 2s 39ms/step - loss: 0.6732 - binary_accuracy: 0.5589 - val_loss: 0.6666 - val_binary_accuracy: 0.5673
Epoch 4/250
56/56 [==============================] - 2s 38ms/step - loss: 0.6638 - binary_accuracy: 0.5706 - val_loss: 0.6563 - val_binary_accuracy: 0.5829
Epoch 5/250
56/56 [==============================] - 2s 38ms/step - loss: 0.6535 - binary_accuracy: 0.5848 - val_loss: 0.6466 - val_binary_accuracy: 0.5968
Epoch 6/250
56/56 [==============================] - 2s 38ms/step - loss: 0.6432 - binary_accuracy: 0.6003 - val_loss: 0.6374 - val_binary_accuracy: 0.6105
Epoch 7/250
56/56 [==============================] - 2s 38ms/ste

In [ ]:
model.fit(X_train, y_train,epochs=500, batch_size=256, validation_data=(X_test, y_test))

Epoch 1/500
56/56 [==============================] - 2s 44ms/step - loss: 0.1353 - binary_accuracy: 0.9366 - val_loss: 0.1550 - val_binary_accuracy: 0.9283
Epoch 2/500
56/56 [==============================] - 2s 41ms/step - loss: 0.1352 - binary_accuracy: 0.9366 - val_loss: 0.1549 - val_binary_accuracy: 0.9284
Epoch 3/500
56/56 [==============================] - 2s 42ms/step - loss: 0.1351 - binary_accuracy: 0.9367 - val_loss: 0.1548 - val_binary_accuracy: 0.9284
Epoch 4/500
56/56 [==============================] - 2s 41ms/step - loss: 0.1350 - binary_accuracy: 0.9367 - val_loss: 0.1548 - val_binary_accuracy: 0.9284
Epoch 5/500
56/56 [==============================] - 2s 40ms/step - loss: 0.1349 - binary_accuracy: 0.9367 - val_loss: 0.1547 - val_binary_accuracy: 0.9284
Epoch 6/500
56/56 [==============================] - 2s 41ms/step - loss: 0.1348 - binary_accuracy: 0.9367 - val_loss: 0.1546 - val_binary_accuracy: 0.9284
Epoch 7/500
56/56 [==============================] - 2s 40ms/ste

In [ ]:
category_vectors = {
    "A": [1,7,8,9,10,16,18],
    "B": [1,2,3,4,5,16,18],
    "K": [1,16,18],
    "L": [7,8,9,10,16,18],
    "M": [11,12,16,18],
    "N": [1,3,4,5,7,16,18],
    "O": [3,4,5,11,12,16,18],
    "P": [2,5,11,13,14,15,16,18],
    "Q": [6,7,8,9,10,16],
    "R": [1,2,3],
    "S": [3,4,5,11,12,16,17,18],
    "T": [1,16,18],
    "C": [7,11,13,14,15,16,18],
    "U": [1,2,3,4,5,16,17,18],
    "V": [1,2,8,16,18],
    "W": [2,12,13,14,15,16,18],
    "X": [16],
    "Y": [1,2,18],
    "Z": [1,18],
    "AA": [6,17],
    "AB": [4,5,11,12,13,16,18],
    "AC": [2,3,16,18,19],
    "AD": [3,4,5,16,18,19],
    "D": [2,11,13,14,15,16,17,18],
    "AE": [2,3,4,5,16],
    "AF": [2,3,4,16,17],
    "AG": [1,2,16],
    "AH": [16,20],
    "AI": [2,3,18],
    "AJ": [6,7,16],
    "AK": [11,12,17,18],
    "E": [2,3,16,18],
    "F": [1,12,13,14,15,16,18],
    "G": [1,5,12,13,14,16,18],
    "H": [11,12,13,14,15,16,18],
    "I": [5,11,12,13,14,16,18],
    "J": [6,7,8,9,10,16,18],
}

In [ ]:
zero_shot_categories = ['J', 'AE', 'H', 'AB', 'E', 'V']

In [ ]:
for d in category_vectors.keys():
    category_vectors[d] = sum(to_categorical([v-1 for v in category_vectors[d]], num_classes=20))

In [ ]:
test_pred = model.predict(X_test)
train_pred = model.predict(X_train)

In [ ]:
def nearest_category(vector, only_zero_shot=False):
    nearest = ""
    value = -1
    if only_zero_shot:
        categories = zero_shot_categories
    else:
        categories = category_vectors.keys() #all categories
    for k in categories:
        d = distance.euclidean(vector, category_vectors[k])
        if d < value or value == -1:
            nearest = k
            value = d
    return nearest

In [ ]:
def hard_decision(predictions, only_zero_shot=False):
    output = []
    for pred in predictions:
        output.append(nearest_category([round(p) for p in pred], only_zero_shot))
    return output

In [ ]:
accuracy_score(hard_decision(y_test), hard_decision(test_pred))

0.6299745977984759

In [ ]:
accuracy_score(hard_decision(y_train), hard_decision(train_pred))

0.680191941288547

In [ ]:
zero_x = loadmat("/content/drive/MyDrive/Research and Project Stuffs/BdSL/featureZero.mat")
zero_y = loadmat("/content/drive/MyDrive/Research and Project Stuffs/BdSL/YZero_arr.mat")

In [ ]:
zero_y.keys()

dict_keys(['__header__', '__version__', '__globals__', 'YTrain_arr'])

In [ ]:
zero_x = zero_x['featureZero']
zero_y = zero_y['YTrain_arr']

In [ ]:
zero_y.shape

(3374, 20)

In [ ]:
zero_pred = model.predict(zero_x)

In [ ]:
accuracy_score(hard_decision(zero_y), hard_decision(zero_pred, only_zero_shot=True))

0.4991108476585655

In [ ]:
accuracy_score(hard_decision(zero_y), hard_decision(zero_pred))

0.08506224066390042

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(hard_decision(zero_y), hard_decision(zero_pred,only_zero_shot=True))

array([[141, 153,  29,  13,   2,  61],
       [  4, 591,   3,  13,   0,  13],
       [ 15,   5, 434,   6,   3,  10],
       [  3,  97,  76, 246,   2, 219],
       [ 82, 271,  66,  26,  25, 160],
       [  2, 137,   2, 217,   0, 247]])

In [ ]:
print(classification_report(hard_decision(zero_y), hard_decision(zero_pred, only_zero_shot=True), target_names=zero_shot_categories))

              precision    recall  f1-score   support

           J       0.57      0.35      0.44       399
          AE       0.47      0.95      0.63       624
           H       0.71      0.92      0.80       473
          AB       0.47      0.38      0.42       643
           P       0.78      0.04      0.08       630
           V       0.35      0.41      0.38       605

    accuracy                           0.50      3374
   macro avg       0.56      0.51      0.46      3374
weighted avg       0.55      0.50      0.44      3374



In [ ]:
from keras.models import model_from_json
# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("modelDensenet.h5")
print("Saved model to disk")

Saved model to disk


**DARKNET53**

In [ ]:
X = loadmat("/content/drive/MyDrive/Research and Project Stuffs/BdSL/featureSeenDarknet.mat")
Y = loadmat("/content/drive/MyDrive/Research and Project Stuffs/BdSL/YTrain_arr.mat")

In [ ]:
X.keys()

dict_keys(['__header__', '__version__', '__globals__', 'featureSeen'])

In [ ]:
X = X['featureSeen']
Y = Y['YTrain_arr']

In [ ]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2,random_state=109) # 70% training and 30% test

In [ ]:
model2 = Sequential()
model2.add(Dense(512, input_dim=1024, activation='relu'))
model2.add(Dense(256, activation='relu'))
model2.add(Dense(128, activation='relu'))
model2.add(Dense(20, activation='sigmoid'))
lr_schedule = keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=1e-6,
    decay_steps=10000,
    decay_rate=0.9)
opt = keras.optimizers.RMSprop(learning_rate=lr_schedule)
model2.compile(optimizer= opt, loss='binary_crossentropy', metrics=['binary_accuracy'])
model2.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               524800    
_________________________________________________________________
dense_1 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_2 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_3 (Dense)              (None, 20)                2580      
Total params: 691,604
Trainable params: 691,604
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model2.fit(X_train, y_train,epochs=1500, batch_size=256, validation_data=(X_test, y_test))

Epoch 1/1500
56/56 [==============================] - 3s 11ms/step - loss: 0.8531 - binary_accuracy: 0.4537 - val_loss: 0.8280 - val_binary_accuracy: 0.4715
Epoch 2/1500
56/56 [==============================] - 0s 4ms/step - loss: 0.8251 - binary_accuracy: 0.4705 - val_loss: 0.8026 - val_binary_accuracy: 0.4883
Epoch 3/1500
56/56 [==============================] - 0s 4ms/step - loss: 0.8000 - binary_accuracy: 0.4863 - val_loss: 0.7791 - val_binary_accuracy: 0.5051
Epoch 4/1500
56/56 [==============================] - 0s 4ms/step - loss: 0.7752 - binary_accuracy: 0.5042 - val_loss: 0.7576 - val_binary_accuracy: 0.5207
Epoch 5/1500
56/56 [==============================] - 0s 4ms/step - loss: 0.7549 - binary_accuracy: 0.5184 - val_loss: 0.7378 - val_binary_accuracy: 0.5362
Epoch 6/1500
56/56 [==============================] - 0s 4ms/step - loss: 0.7367 - binary_accuracy: 0.5336 - val_loss: 0.7198 - val_binary_accuracy: 0.5521
Epoch 7/1500
56/56 [==============================] - 0s 4ms/st

In [ ]:
zero_x = loadmat("/content/drive/MyDrive/Research and Project Stuffs/BdSL/featuresZeroTestDark.mat")
zero_y = loadmat("/content/drive/MyDrive/Research and Project Stuffs/BdSL/LabelsZeroTestDark.mat")
zero_x = zero_x['featureszerotest']
zero_y = zero_y['YTest2']

In [ ]:
test_pred = model2.predict(X_test)
train_pred = model2.predict(X_train)
zero_pred = model2.predict(zero_x)

In [ ]:
print(accuracy_score(hard_decision(y_train), hard_decision(train_pred)))
print(accuracy_score(hard_decision(y_test), hard_decision(test_pred)))
print(accuracy_score(hard_decision(zero_y), hard_decision(zero_pred, only_zero_shot=True)))
print(accuracy_score(hard_decision(zero_y), hard_decision(zero_pred)))

0.7189330322489591
0.6658199266158623
0.5378111789572569
0.18694222639736965


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(hard_decision(zero_y), hard_decision(zero_pred,only_zero_shot=True))

array([[100,  52,  42,  34,   7,  31],
       [  6, 206, 174,   1,  21,   8],
       [ 15,  25, 217,  29,   6,   6],
       [ 12,   1,   4, 278,   0,  21],
       [  7,   1, 106,  48, 181,  86],
       [  2,   9,  95,   5, 130, 163]])

In [ ]:
print(classification_report(hard_decision(zero_y), hard_decision(zero_pred, only_zero_shot=True), target_names=zero_shot_categories))

              precision    recall  f1-score   support

           J       0.70      0.38      0.49       266
          AE       0.70      0.50      0.58       416
           H       0.34      0.73      0.46       298
          AB       0.70      0.88      0.78       316
           E       0.52      0.42      0.47       429
           V       0.52      0.40      0.45       404

    accuracy                           0.54      2129
   macro avg       0.58      0.55      0.54      2129
weighted avg       0.58      0.54      0.54      2129



In [ ]:
model2.fit(X_train, y_train,epochs=5000, batch_size=256, validation_data=(X_test, y_test))

Streaming output truncated to the last 5000 lines.
Epoch 2501/5000
56/56 [==============================] - 0s 6ms/step - loss: -0.3560 - binary_accuracy: 0.9588 - val_loss: -0.2365 - val_binary_accuracy: 0.9450
Epoch 2502/5000
56/56 [==============================] - 0s 5ms/step - loss: -0.3561 - binary_accuracy: 0.9588 - val_loss: -0.2366 - val_binary_accuracy: 0.9450
Epoch 2503/5000
56/56 [==============================] - 0s 5ms/step - loss: -0.3562 - binary_accuracy: 0.9588 - val_loss: -0.2367 - val_binary_accuracy: 0.9450
Epoch 2504/5000
56/56 [==============================] - 0s 6ms/step - loss: -0.3564 - binary_accuracy: 0.9588 - val_loss: -0.2368 - val_binary_accuracy: 0.9450
Epoch 2505/5000
56/56 [==============================] - 0s 8ms/step - loss: -0.3565 - binary_accuracy: 0.9588 - val_loss: -0.2369 - val_binary_accuracy: 0.9450
Epoch 2506/5000
56/56 [==============================] - 0s 6ms/step - loss: -0.3566 - binary_accuracy: 0.9587 - val_loss: -0.2370 - val_binary_

In [ ]:
test_pred = model2.predict(X_test)
train_pred = model2.predict(X_train)
zero_pred = model2.predict(zero_x)

In [ ]:
print(accuracy_score(hard_decision(y_train), hard_decision(train_pred)))
print(accuracy_score(hard_decision(y_test), hard_decision(test_pred)))
print(accuracy_score(hard_decision(zero_y), hard_decision(zero_pred, only_zero_shot=True)))
print(accuracy_score(hard_decision(zero_y), hard_decision(zero_pred)))

0.7447604262225672
0.6838837143663562
0.5434476279943635
0.16956317519962424


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(hard_decision(zero_y), hard_decision(zero_pred,only_zero_shot=True))

array([[110,  46,  32,  35,  10,  33],
       [  6, 196, 183,   2,  20,   9],
       [  8,  18, 224,  36,   7,   5],
       [ 13,   0,   3, 282,   1,  17],
       [  3,   2,  99,  54, 190,  81],
       [  3,  16,  81,   9, 140, 155]])

In [ ]:
confusion_matrix(hard_decision(zero_y), hard_decision(zero_pred))

array([[0, 0, 0, ..., 0, 0, 0],
       [4, 6, 3, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
print(classification_report(hard_decision(zero_y), hard_decision(zero_pred, only_zero_shot=True), target_names=zero_shot_categories))

              precision    recall  f1-score   support

           J       0.77      0.41      0.54       266
          AE       0.71      0.47      0.56       416
           H       0.36      0.75      0.49       298
          AB       0.67      0.89      0.77       316
           E       0.52      0.44      0.48       429
           V       0.52      0.38      0.44       404

    accuracy                           0.54      2129
   macro avg       0.59      0.56      0.55      2129
weighted avg       0.59      0.54      0.54      2129



**Random** **Result**


In [ ]:
model2.fit(X_train, y_train,epochs=0, batch_size=256, validation_data=(X_test, y_test))

In [ ]:
test_pred = model2.predict(X_test)
train_pred = model2.predict(X_train)
zero_pred = model2.predict(zero_x)

In [ ]:
print(accuracy_score(hard_decision(y_train), hard_decision(train_pred)))
print(accuracy_score(hard_decision(y_test), hard_decision(test_pred)))
print(accuracy_score(hard_decision(zero_y), hard_decision(zero_pred, only_zero_shot=True)))
print(accuracy_score(hard_decision(zero_y), hard_decision(zero_pred)))

0.026956460376825912
0.023990968106124753
0.1611085016439643
0.0014091122592766556


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(hard_decision(zero_y), hard_decision(zero_pred,only_zero_shot=True))

array([[  1, 166,   6,   1,  91,   1],
       [  3, 185,  28,  12, 178,  10],
       [ 18, 139,  10,  16, 115,   0],
       [ 16, 165,  16,  39,  77,   3],
       [  3, 246,  54,  18, 106,   2],
       [  8, 185,  11,  12, 186,   2]])